import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Bitter } from 'next/font/google'

const bitter = Bitter({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ratnamik Metal - India",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
       <body className={`${bitter.className} min-h-full flex flex-col overflow-x-hidden`}>
        {children}
      </body>
    </html>
  );
}